"""`create_note` tool：在 default_note_dir 或指定路径下创建笔记。"""

from __future__ import annotations

from dataclasses import asdict
from pathlib import Path

from ..base import ToolContext, ToolResult
from .._utils import slugify

PROMPT = (Path(__file__).parent / "prompt.md").read_text(encoding="utf-8")


def create_note(args: dict[str, object], context: ToolContext) -> ToolResult:
    title = str(args.get("title") or "Untitled Note").strip()
    path = str(args.get("path") or f"{context.default_note_dir}/{slugify(title)}.md").strip()
    content = str(args.get("content") or f"# {title}\n\nGenerated by more agent.").strip()
    events = [{"type": "tool_started", "tool": "create_note", "target": path}]
    note = context.note_service.create_note(path, content, title=title, source_type="agent")
    events.append({"type": "note_created", "note": asdict(note.meta)})
    events.append({"type": "tool_finished", "tool": "create_note", "target": path})
    return ToolResult(
        ok=True,
        tool="create_note",
        summary=f"Created a new note at `{note.meta.relative_path}` with title `{note.meta.title}`.",
        citations=[note.meta.relative_path],
        events=events,
        payload={"note": asdict(note.meta)},
    )


PARAMETERS: dict[str, object] = {
    "type": "object",
    "properties": {
        "title": {
            "type": "string",
            "description": "Human-readable title (also stored in frontmatter). Defaults to 'Untitled Note'.",
        },
        "path": {
            "type": "string",
            "description": "Workspace-relative path ending in .md. If omitted, derived as '{default_note_dir}/{slug(title)}.md'.",
        },
        "content": {
            "type": "string",
            "description": "Full markdown body (excluding frontmatter). Omit for a skeleton '# {title}\\n\\nGenerated by more agent.'.",
        },
    },
    "additionalProperties": False,
}


def register(registry) -> None:
    registry.register(
        "create_note",
        create_note,
        kind="native",
        description=PROMPT,
        parameters=PARAMETERS,
    )


__all__ = ["PARAMETERS", "PROMPT", "create_note", "register"]
